version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: medusa
      POSTGRES_PASSWORD: medusa_password
      POSTGRES_DB: medusa_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - medusa-network

  medusa:
    image: nagaraju7876482/medusa-backend-dev:${{ env.VERSION }}
    environment:
      # The connection string to the Postgres container
      DATABASE_URL: postgres://medusa:medusa_password@postgres:5432/medusa_db
      # Cross-origin requests allowed from Medusa admin and store
      MEDUSA_ADMIN_CORS: http://localhost:7000
      MEDUSA_STORE_CORS: http://localhost:8000
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    networks:
      - medusa-network

volumes:
  postgres-data:

networks:
  medusa-network:
    driver: bridge
