name: Infrastructure Setup

# Triggers on changes within the 'infrastructure/' folder and manual dispatch
on:
  push:
    paths:
      - 'terraform/**'  # Triggers only when files in this folder change
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  infra-setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Apply
        id: terraform_apply
        run: |
          cd terraform
          terraform apply -auto-approve
           EC2_HOST=$(terraform output -raw instance_ip)
          echo "EC2_HOST=${EC2_HOST}" >> $GITHUB_ENV

      - name: Debug environment variables
        run: |
          echo "EC2_HOST=${{ env.EC2_HOST }}"

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Install Docker and Docker Compose
        run: |
          ssh -t -o StrictHostKeyChecking=no ubuntu@${{ env.EC2_HOST }} << 'EOF'
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo systemctl enable docker
            sudo systemctl start docker
            sudo curl -L "https://github.com/docker/compose/releases/download/2.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker --version
            docker-compose --version
          EOF
